CREATE TABLE settlement_runs(
    id UUID PRIMARY KEY,
    available_settlement_balance NUMERIC(20,4) NOT NULL CHECK (available_settlement_balance >= 0),
    total_settlement_consumed  NUMERIC(20,4 ) NOT NULL CHECK (total_settlement_consumed >= 0 AND total_settlement_consumed <= available_settlement_balance),
    total_expected_fee NUMERIC(20,4) NOT NULL CHECK (total_expected_fee >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE settlement_instructions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id UUID NOT NULL REFERENCES settlement_runs(id),
    instruction_reference VARCHAR(50) NOT NULL,
    instruction_amount NUMERIC(20,4) NOT NULL CHECK (instruction_amount > 0),
    expected_fee NUMERIC(20,4) NOT NULL CHECK (expected_fee >= 0),
    selected BOOLEAN NOT NULL
);

CREATE INDEX idx_settlement_runs_created_at
    ON settlement_runs (created_at DESC, id DESC);

CREATE INDEX idx_settlement_instructions_run_id
    ON settlement_instructions (run_id);